name: eslint

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          make install
        env:
          CI: true  
      - name: Run Linter
        run: |
          make lint
      - name: Test & publish code coverage
        # Publish code coverage on Code Climate
        # https://github.com/paambaati/codeclimate-action
        uses:  paambaati/codeclimate-action@v2.7.4
        # Add Code Climate secret key
        env:
          CODECLIMAT_KEYS_ID: ${{ secrets.CODECLIMAT_KEYS_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true
